import os
import numpy as np
import pandas as pd
import rasterio
from rasterio.warp import reproject, Resampling
from rasterio.transform import from_origin
import joblib

# ============================================================
# CONFIG
# ============================================================

BASE_DIR = r"C:\Users\Naveen\Desktop\YHACK-LANDSLIDE"

RAINFALL_FILE = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "rainfall",
    "meghalaya_rainfall_spatial.csv"
)

MODEL_FILE = os.path.join(
    BASE_DIR,
    "models",
    "random_forest_static.joblib"
)

ELEVATION_FILE = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "terrain",
    "elevation.tif"
)

SLOPE_FILE = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "terrain",
    "slope.tif"
)

ASPECT_FILE = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "terrain",
    "aspect.tif"
)

CURVATURE_FILE = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "terrain",
    "curvature.tif"
)

LANDCOVER_FILE = os.path.join(
    BASE_DIR,
    "data",
    "raw",
    "landcover",
    "meghalaya_worldcover_2021_10m.tif"
)

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "risk"
)

SCENARIO_DATE = "2022-06-21"

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def percentile_to_score(value):
    """
    Convert rainfall amount to trigger score using
    the percentile thresholds already calculated
    in the rainfall dataset.
    """

    if pd.isna(value):
        return np.nan

    if value <= 0:
        return 0.10
    elif value <= 0.25:
        return 0.30
    elif value <= 0.50:
        return 0.50
    elif value <= 0.75:
        return 0.70
    elif value <= 0.90:
        return 0.90
    else:
        return 1.00


def rainfall_trigger_score(row):
    """
    Calculate weighted rainfall trigger.

    We intentionally use the trigger_score columns
    already generated by create_rainfall_features.py.
    """

    scores = [
        row.get("rainfall_1d_score", np.nan),
        row.get("rainfall_3d_score", np.nan),
        row.get("rainfall_7d_score", np.nan),
        row.get("rainfall_15d_score", np.nan),
        row.get("rainfall_30d_score", np.nan),
    ]

    weights = np.array([
        0.15,
        0.15,
        0.30,
        0.20,
        0.20
    ])

    scores = np.array(scores, dtype=float)

    valid = ~np.isnan(scores)

    if not valid.any():
        return np.nan

    weights_valid = weights[valid]
    scores_valid = scores[valid]

    weights_valid = weights_valid / weights_valid.sum()

    return float(np.sum(scores_valid * weights_valid))


def create_rainfall_grid(df):
    """
    Convert the rainfall CSV for the selected date
    into a small regular raster grid.

    Automatically detects latitude/longitude column names.
    """

    print("\nRainfall CSV columns:")
    print(list(df.columns))

    # --------------------------------------------------------
    # Detect latitude column
    # --------------------------------------------------------

    lat_candidates = [
        "lat",
        "latitude",
        "LATITUDE",
        "Latitude"
    ]

    lon_candidates = [
        "lon",
        "longitude",
        "LONGITUDE",
        "Longitude"
    ]

    lat_col = next(
        (col for col in lat_candidates if col in df.columns),
        None
    )

    lon_col = next(
        (col for col in lon_candidates if col in df.columns),
        None
    )

    if lat_col is None or lon_col is None:

        raise ValueError(
            "\nCould not detect latitude/longitude columns.\n"
            f"Available columns: {list(df.columns)}\n"
            "Expected something like lat/lon or latitude/longitude."
        )

    print(
        f"Using latitude column: {lat_col}"
    )

    print(
        f"Using longitude column: {lon_col}"
    )

    # --------------------------------------------------------
    # Get unique coordinates
    # --------------------------------------------------------

    lats = np.sort(
        df[lat_col].astype(float).unique()
    )

    lons = np.sort(
        df[lon_col].astype(float).unique()
    )

    rainfall_grid = np.full(
        (len(lats), len(lons)),
        np.nan,
        dtype=np.float32
    )

    # --------------------------------------------------------
    # Fill rainfall grid
    # --------------------------------------------------------

    lat_lookup = {
        value: idx
        for idx, value in enumerate(lats)
    }

    lon_lookup = {
        value: idx
        for idx, value in enumerate(lons)
    }

    for _, row in df.iterrows():

        lat = float(row[lat_col])
        lon = float(row[lon_col])

        lat_idx = lat_lookup[lat]
        lon_idx = lon_lookup[lon]

        rainfall_grid[
            lat_idx,
            lon_idx
        ] = row["rainfall_trigger"]

    return rainfall_grid, lats, lons
    """
    Convert the rainfall CSV for the selected date
    into a small regular raster grid.

    Rainfall source:
        ~0.25 degree resolution
        5 x 13 Meghalaya cells
    """

    lats = np.sort(df["lat"].unique())
    lons = np.sort(df["lon"].unique())

    rainfall_grid = np.full(
        (len(lats), len(lons)),
        np.nan,
        dtype=np.float32
    )

    for _, row in df.iterrows():

        lat_idx = np.where(lats == row["lat"])[0][0]
        lon_idx = np.where(lons == row["lon"])[0][0]

        rainfall_grid[lat_idx, lon_idx] = row["rainfall_trigger"]

    return rainfall_grid, lats, lons


def reproject_rainfall_to_terrain(
    rainfall_grid,
    lats,
    lons,
    terrain_profile
):
    """
    Efficiently resample the coarse rainfall trigger
    grid onto the 30 m terrain grid.

    Nearest-neighbour is used because rainfall cells are
    categorical/score-based rather than continuous 30 m data.
    """

    source_height, source_width = rainfall_grid.shape

    resolution_x = float(np.median(np.diff(lons)))
    resolution_y = float(np.median(np.diff(lats)))

    # Rainfall coordinates represent cell centers.
    source_transform = from_origin(
        float(lons.min()) - resolution_x / 2,
        float(lats.max()) + resolution_y / 2,
        resolution_x,
        resolution_y
    )

    destination = np.full(
        (
            terrain_profile["height"],
            terrain_profile["width"]
        ),
        np.nan,
        dtype=np.float32
    )

    reproject(
        source=rainfall_grid,
        destination=destination,
        src_transform=source_transform,
        src_crs="EPSG:4326",
        dst_transform=terrain_profile["transform"],
        dst_crs=terrain_profile["crs"],
        resampling=Resampling.nearest,
        src_nodata=np.nan,
        dst_nodata=np.nan
    )

    return destination


def resample_landcover_to_terrain(
    terrain_profile
):
    """
    Resample ESA WorldCover 10 m raster onto
    the 30 m terrain grid.

    Nearest neighbour is mandatory because
    WorldCover classes are categorical.
    """

    print("\n[5] Resampling WorldCover 10 m -> terrain 30 m...")

    destination = np.zeros(
        (
            terrain_profile["height"],
            terrain_profile["width"]
        ),
        dtype=np.float32
    )

    with rasterio.open(LANDCOVER_FILE) as src:

        print("WorldCover dimensions:", (src.height, src.width))
        print("WorldCover CRS:", src.crs)

        reproject(
            source=rasterio.band(src, 1),
            destination=destination,
            src_transform=src.transform,
            src_crs=src.crs,
            dst_transform=terrain_profile["transform"],
            dst_crs=terrain_profile["crs"],
            resampling=Resampling.nearest,
            src_nodata=src.nodata,
            dst_nodata=0
        )

    print("WorldCover successfully aligned to terrain grid.")

    return destination


def save_raster(
    output_file,
    array,
    profile,
    dtype="float32",
    nodata=-9999
):

    output_profile = profile.copy()

    output_profile.update(
        dtype=dtype,
        count=1,
        compress="deflate",
        predictor=2,
        nodata=nodata
    )

    output_array = np.array(array, copy=True)

    if np.issubdtype(np.dtype(dtype), np.floating):

        output_array = np.where(
            np.isfinite(output_array),
            output_array,
            nodata
        )

    with rasterio.open(
        output_file,
        "w",
        **output_profile
    ) as dst:

        dst.write(
            output_array.astype(dtype),
            1
        )


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 75)
    print("YHACK LANDSLIDE AI - DYNAMIC RISK ENGINE")
    print("=" * 75)

    # --------------------------------------------------------
    # 1. LOAD RAINFALL SCENARIO
    # --------------------------------------------------------

    print("\n[1] Loading rainfall scenario...")

    rainfall_df = pd.read_csv(
        RAINFALL_FILE
    )

    rainfall_df["date"] = pd.to_datetime(
        rainfall_df["date"]
    )

    scenario = rainfall_df[
        rainfall_df["date"] == pd.Timestamp(SCENARIO_DATE)
    ].copy()

    if scenario.empty:
        raise ValueError(
            f"No rainfall data found for {SCENARIO_DATE}"
        )

    print("Scenario date:", SCENARIO_DATE)
    print("Rainfall cells:", len(scenario))

    # --------------------------------------------------------
    # 2. CALCULATE RAINFALL TRIGGER
    # --------------------------------------------------------

    print("\n[2] Calculating rainfall trigger...")

    scenario["rainfall_trigger"] = scenario.apply(
        rainfall_trigger_score,
        axis=1
    )

    print("\nRainfall trigger statistics:")

    print(
        scenario["rainfall_trigger"].describe()
    )

    # --------------------------------------------------------
    # 3. LOAD RANDOM FOREST
    # --------------------------------------------------------

    print("\n[3] Loading Random Forest model...")

    model = joblib.load(
        MODEL_FILE
    )

    print("Model loaded:", MODEL_FILE)

    # --------------------------------------------------------
    # 4. LOAD TERRAIN
    # --------------------------------------------------------

    print("\n[4] Loading terrain features...")

    with rasterio.open(ELEVATION_FILE) as src:

        elevation = src.read(1).astype(np.float32)

        terrain_profile = src.profile.copy()

        terrain_transform = src.transform
        terrain_crs = src.crs

        height = src.height
        width = src.width

    with rasterio.open(SLOPE_FILE) as src:

        slope = src.read(1).astype(np.float32)

        if src.shape != (height, width):
            raise ValueError(
                "Slope raster does not match elevation raster."
            )

    with rasterio.open(ASPECT_FILE) as src:

        aspect = src.read(1).astype(np.float32)

        if src.shape != (height, width):
            raise ValueError(
                "Aspect raster does not match elevation raster."
            )

    with rasterio.open(CURVATURE_FILE) as src:

        curvature = src.read(1).astype(np.float32)

        if src.shape != (height, width):
            raise ValueError(
                "Curvature raster does not match elevation raster."
            )

    print(
        "Terrain dimensions:",
        (height, width)
    )

    print(
        "Terrain CRS:",
        terrain_crs
    )

    # --------------------------------------------------------
    # 5. RESAMPLE LANDCOVER
    # --------------------------------------------------------

    landcover = resample_landcover_to_terrain(
        terrain_profile
    )

    # --------------------------------------------------------
    # 6. BUILD RAINFALL TRIGGER GRID
    # --------------------------------------------------------

    print("\n[6] Creating rainfall trigger raster...")

    rainfall_grid, rainfall_lats, rainfall_lons = (
        create_rainfall_grid(scenario)
    )

    print(
        "Rainfall grid:",
        rainfall_grid.shape
    )

    rainfall_trigger_raster = (
        reproject_rainfall_to_terrain(
            rainfall_grid,
            rainfall_lats,
            rainfall_lons,
            terrain_profile
        )
    )

    valid_rainfall = np.isfinite(
        rainfall_trigger_raster
    )

    print(
        "Terrain pixels receiving rainfall data:",
        int(valid_rainfall.sum())
    )

    # --------------------------------------------------------
    # 7. RANDOM FOREST SUSCEPTIBILITY
    # --------------------------------------------------------

    print("\n[7] Predicting landslide susceptibility...")

    total_pixels = height * width

    print(
        "Total terrain pixels:",
        f"{total_pixels:,}"
    )

    susceptibility = np.full(
        (height, width),
        np.nan,
        dtype=np.float32
    )

    # Valid pixels

    valid_mask = (
        np.isfinite(elevation)
        &
        np.isfinite(slope)
        &
        np.isfinite(aspect)
        &
        np.isfinite(curvature)
        &
        (landcover > 0)
    )

    valid_mask &= valid_rainfall

    valid_indices = np.flatnonzero(
        valid_mask.ravel()
    )

    print(
        "Valid prediction pixels:",
        f"{len(valid_indices):,}"
    )

    # --------------------------------------------------------
    # PREDICT IN CHUNKS
    # --------------------------------------------------------

    CHUNK_SIZE = 500_000

    flat_elevation = elevation.ravel()
    flat_slope = slope.ravel()
    flat_aspect = aspect.ravel()
    flat_curvature = curvature.ravel()
    flat_landcover = landcover.ravel()

    susceptibility_flat = susceptibility.ravel()

    for start in range(
        0,
        len(valid_indices),
        CHUNK_SIZE
    ):

        end = min(
            start + CHUNK_SIZE,
            len(valid_indices)
        )

        idx = valid_indices[start:end]

        X = np.column_stack([
            flat_elevation[idx],
            flat_slope[idx],
            flat_aspect[idx],
            flat_curvature[idx],
            flat_landcover[idx]
        ])

        probabilities = model.predict_proba(
            X
        )[:, 1]

        susceptibility_flat[idx] = (
            probabilities.astype(np.float32)
        )

        print(
            f"  Predicted {end:,} / "
            f"{len(valid_indices):,} pixels"
        )

    susceptibility = susceptibility_flat.reshape(
        height,
        width
    )

    print(
        "\nSusceptibility statistics:"
    )

    valid_susc = susceptibility[
        np.isfinite(susceptibility)
    ]

    print(
        pd.Series(valid_susc).describe()
    )

    # --------------------------------------------------------
    # 8. DYNAMIC RISK
    # --------------------------------------------------------

    print("\n[8] Calculating dynamic risk...")

    dynamic_risk = (
        susceptibility
        *
        rainfall_trigger_raster
    )

    dynamic_risk[
        ~np.isfinite(dynamic_risk)
    ] = np.nan

    valid_risk = dynamic_risk[
        np.isfinite(dynamic_risk)
    ]

    print(
        "\nDynamic risk statistics:"
    )

    print(
        pd.Series(valid_risk).describe()
    )

    # --------------------------------------------------------
    # 9. RISK CATEGORIES
    # --------------------------------------------------------

    print("\n[9] Creating risk categories...")

    risk_class = np.zeros(
        (height, width),
        dtype=np.uint8
    )

    valid = np.isfinite(
        dynamic_risk
    )

    # These are presentation thresholds for the MVP.
    # They are NOT scientific universal thresholds.

    risk_class[
        valid & (dynamic_risk < 0.20)
    ] = 1

    risk_class[
        valid
        & (dynamic_risk >= 0.20)
        & (dynamic_risk < 0.35)
    ] = 2

    risk_class[
        valid
        & (dynamic_risk >= 0.35)
        & (dynamic_risk < 0.50)
    ] = 3

    risk_class[
        valid
        & (dynamic_risk >= 0.50)
        & (dynamic_risk < 0.65)
    ] = 4

    risk_class[
        valid
        & (dynamic_risk >= 0.65)
        & (dynamic_risk < 0.80)
    ] = 5

    risk_class[
        valid & (dynamic_risk >= 0.80)
    ] = 6

    class_names = {
        1: "LOW",
        2: "MODERATE",
        3: "ELEVATED",
        4: "HIGH",
        5: "VERY HIGH",
        6: "EXTREME"
    }

    print("\nRisk distribution:")

    for class_id, name in class_names.items():

        count = int(
            np.sum(
                risk_class == class_id
            )
        )

        percentage = (
            count / max(int(valid.sum()), 1)
        ) * 100

        print(
            f"{name:12s}: "
            f"{count:,} pixels "
            f"({percentage:.2f}%)"
        )

    # --------------------------------------------------------
    # 10. SAVE OUTPUTS
    # --------------------------------------------------------

    print("\n[10] Saving output rasters...")

    susceptibility_file = os.path.join(
        OUTPUT_DIR,
        "susceptibility_30m.tif"
    )

    rainfall_file = os.path.join(
        OUTPUT_DIR,
        f"rainfall_trigger_{SCENARIO_DATE}.tif"
    )

    dynamic_file = os.path.join(
        OUTPUT_DIR,
        f"dynamic_risk_{SCENARIO_DATE}.tif"
    )

    risk_class_file = os.path.join(
        OUTPUT_DIR,
        f"risk_class_{SCENARIO_DATE}.tif"
    )

    save_raster(
        susceptibility_file,
        susceptibility,
        terrain_profile
    )

    save_raster(
        rainfall_file,
        rainfall_trigger_raster,
        terrain_profile
    )

    save_raster(
        dynamic_file,
        dynamic_risk,
        terrain_profile
    )

    save_raster(
        risk_class_file,
        risk_class,
        terrain_profile,
        dtype="uint8",
        nodata=0
    )

    # --------------------------------------------------------
    # FINISH
    # --------------------------------------------------------

    print("\n" + "=" * 75)
    print("DYNAMIC RISK ENGINE COMPLETE")
    print("=" * 75)

    print("\nCreated:")

    print(
        "1.",
        susceptibility_file
    )

    print(
        "2.",
        rainfall_file
    )

    print(
        "3.",
        dynamic_file
    )

    print(
        "4.",
        risk_class_file
    )

    print("\nScenario:", SCENARIO_DATE)

    print(
        "\nIMPORTANT:"
        "\nRainfall is based on the available ~0.25° rainfall grid."
        "\nIt is NOT 30 m rainfall."
        "\nThe 30 m raster is only the output/display grid."
    )


if __name__ == "__main__":
    main()